const PRODUCTS = [
  {
    id: 3,
    name: 'Urban Canvas',
    brand: 'Stridelab',
    price: 95,
    color: 'Natural / Bone',
    category: 'Lifestyle',
    sizes: [6, 7, 8, 8.5, 9, 9.5, 10, 11, 12],
    images: ['images/3_1.jpg', 'images/3_2.jpg', 'images/3_3.jpg'],
    description: 'Canvas upper with vulcanized sole. The Urban Canvas is a timeless low-top that pairs with everything.',
  },
  {
    id: 4,
    name: 'Peak Series',
    brand: 'Apex Gear',
    price: 160,
    color: 'Black / Carbon',
    category: 'Performance',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12, 13],
    images: ['images/4_1.jpg', 'images/4_2.jpg', 'images/4_3.jpg'],
    description: 'Built for athletes who demand more. Carbon-fibre reinforced plate, full-length foam, and precision-engineered fit.',
  },
  {
    id: 5,
    name: 'Drift Classic',
    brand: 'Stridelab',
    price: 125,
    color: 'Cream / Gum',
    category: 'Lifestyle',
    sizes: [6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 11],
    images: ['images/5_1.jpg', 'images/5_2.jpg', 'images/5_3.jpg'],
    description: 'A retro silhouette reissued in premium suede. The Drift Classic carries archive DNA into modern wardrobe territory.',
  },
  {
    id: 6,
    name: 'Volt Trail',
    brand: 'Kinetic',
    price: 145,
    color: 'Olive / Sand',
    category: 'Trail',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    images: ['images/6_1.jpg', 'images/6_2.jpg', 'images/6_3.jpg'],
    description: 'Aggressive lug outsole meets trail-ready upper. The Volt Trail moves from mud to street without missing a step.',
  },
  {
    id: 7,
    name: 'Core Sport',
    brand: 'Apex Gear',
    price: 115,
    color: 'White / Silver',
    category: 'Training',
    sizes: [6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 11, 12],
    images: ['images/7_1.jpg', 'images/7_2.jpg', 'images/7_3.jpg'],
    description: 'Flat, stable, versatile. The Core Sport is the go-to for the gym — lateral support and a low-profile build for lifts and drills.',
  },
  {
    id: 8,
    name: 'Nocturne',
    brand: 'Stridelab',
    price: 175,
    color: 'Midnight / Obsidian',
    category: 'Lifestyle',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    images: ['images/8_1.jpg', 'images/8_2.jpg', 'images/8_3.jpg'],
    description: 'All-black premium leather upper with tonal branding. The Nocturne is the understated choice for those who prefer quiet confidence.',
  },
  {
    id: 9,
    name: 'Apex Speed',
    brand: 'Kinetic',
    price: 190,
    color: 'Signal / White',
    category: 'Running',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12, 13],
    images: ['images/9_1.jpg', 'images/9_2.jpg', 'images/9_3.jpg'],
    description: 'Race-day speed in a daily trainer package. Super-foam midsole and a knit upper combine for a fast, locked-in feel.',
  },
  {
    id: 10,
    name: 'Terra Mid',
    brand: 'Kinetic',
    price: 130,
    color: 'Brown / Tan',
    category: 'Outdoor',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    images: ['images/10_1.jpg', 'images/10_2.jpg'],
    description: 'Mid-cut construction with water-resistant nubuck. The Terra Mid is built for weekend explorers and everyday pragmatists alike.',
  },
  {
    id: 11,
    name: 'Haze Low',
    brand: 'Stridelab',
    price: 105,
    color: 'Fog / Light Grey',
    category: 'Lifestyle',
    sizes: [6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 11],
    images: ['images/11_1.jpg', 'images/11_2.jpg'],
    description: 'Soft neoprene collar and washed canvas upper. The Haze Low has that lived-in look from day one.',
  },
  {
    id: 12,
    name: 'Circuit Pro',
    brand: 'Apex Gear',
    price: 155,
    color: 'Electric Blue / Black',
    category: 'Performance',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12, 13],
    images: ['images/12_1.jpg', 'images/12_2.jpg'],
    description: 'High-rebound cushioning platform for high-intensity training sessions. The Circuit Pro keeps up with whatever you throw at it.',
  },
];
